### PR TITLE
Added preview handling of space key to prevent crash.

### LINKED ISSUE #2: Adding spaces throws an exception
While editing the text box if the user enters two spaces an exception is thrown at IPControl.cs line 72:
`IPAddress = IPAddress.Parse(CorrectedAddress);`

> System.FormatException: An invalid IP address was specified.
> 
>  ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
>    --- End of inner exception stack trace ---
>    at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
>    at System.Net.IPAddress.Parse(String ipString)
>    at IntruderLeather.Controls.IpAddress.IpControl.OnTextChanged(TextChangedEventArgs e) in C:\src\IpControl\IpControl\IpControl.cs:line 72
>    at System.Windows.Controls.Primitives.TextBoxBase.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
>    at System.Windows.Controls.TextBox.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
>    at System.Windows.Documents.TextContainer.EndChange(Boolean skipEvents)
>    at System.Windows.Documents.TextContainer.System.Windows.Documents.ITextContainer.EndChange(Boolean skipEvents)
>    at System.Windows.Documents.TextRangeBase.EndChange(ITextRange thisRange, Boolean disableScroll, Boolean skipEvents)
>    at System.Windows.Documents.TextRange.System.Windows.Documents.ITextRange.EndChange(Boolean disableScroll, Boolean skipEvents)
>    at System.Windows.Documents.TextRange.ChangeBlock.System.IDisposable.Dispose()
>    at System.Windows.Controls.TextBox.OnTextPropertyChanged(String oldText, String newText)
>    at System.Windows.Controls.TextBox.OnTextPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
>    at System.Windows.Controls.TextBox.set_Text(String value)
>    at IntruderLeather.Controls.IpAddress.IpControl.SetText(String text) in C:\src\IpControl\IpControl\IpControl.cs:line 56
>    at IntruderLeather.Controls.IpAddress.IpControl.AddressComponent.set_Text(String value) in C:\src\IpControl\IpControl\IpControl.cs:line 462
>    at IntruderLeather.Controls.IpAddress.IpControl.AddressComponent.Normalize() in C:\src\IpControl\IpControl\IpControl.cs:line 520
>    at IntruderLeather.Controls.IpAddress.IpControl.OnSelectionChanged(RoutedEventArgs e) in C:\src\IpControl\IpControl\IpControl.cs:line 251
>    at System.Windows.Controls.Primitives.TextBoxBase.OnSelectionChangedInternal(Object sender, EventArgs e)
>    at System.Windows.Documents.TextSelection.System.Windows.Documents.ITextRange.NotifyChanged(Boolean disableScroll, Boolean skipEvents)
>    at System.Windows.Documents.TextRangeBase.EndChange(ITextRange thisRange, Boolean disableScroll, Boolean skipEvents)
>    at System.Windows.Documents.TextRange.System.Windows.Documents.ITextRange.EndChange(Boolean disableScroll, Boolean skipEvents)
>    at System.Windows.Documents.TextRange.ChangeBlock.System.IDisposable.Dispose()
>    at System.Windows.Documents.TextEditorTyping.DoTextInput(TextEditor This, String textData, Boolean isInsertKeyToggled, Boolean acceptControlCharacters)
>    at System.Windows.Documents.TextEditorTyping.TextInputItem.Do()
>    at System.Windows.Documents.TextEditorTyping.ScheduleInput(TextEditor This, InputItem item)
>    at System.Windows.Documents.TextEditorTyping.OnSpace(Object sender, ExecutedRoutedEventArgs e)
>    at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
>    at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
>    at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
>    at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
>    at System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
>    at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
>    at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
>    at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
>    at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
>    at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
>    at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.Run()
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run()
>    at IpControl.App.Main()

### PR DESCRIPTION
**Pull request by Gishe**
The space key is not sent through the OnTextInput logic and skips the validation checks in that area.
Fixes #2

### CODE REVIEW

**Review by jamiehankins — APPROVED** [review]
LGTM

**Comment by Gishe** [comment]
@jamiehankins Would it be possible to release a revision with this on Nuget to fix this issue? I really like the control it works great.

**Comment by jamiehankins** [comment]
@Gishe I'll try to do that soon.

**Comment by jamiehankins** [comment]
@Gishe 1.0.2 is pushed. The NuGet people are validating, so should be available soon.

Thanks much for your submission!

**Pull request merged**
